#!/bin/bash

NAME="web3diag"
PLATFORMS="linux-amd64 darwin-amd64"

die(){
    echo "ERROR: $*" 1>&2
    exit 1
}

echo "Checking dependencies";	go mod tidy || die "Failed to format"

echo "Formatting code";	go fmt ./... || die "Failed to format"

#echo "Linting code";	golint ./... || die "Failed to lint"

echo "Vetting code";	go vet ./... || die "Failed to vet"

echo "Testing code";	go test ./... || die "Test suite failed"

mkdir -p targets

for platform in $PLATFORMS
do
    os=$(echo $platform | cut -f 1 -d -)
    arch=$(echo $platform | cut -f 2 -d -)
    echo "Building code for $os on $arch"
    env GOOS=$os GOARCH=$arch go build -o targets/${NAME}-$platform
done
